baseURL = "https://ritter4u.github.io"
languageCode = "ko"
DefaultContentLanguage = "ko"
title = "Website of Jane Doe"
# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = ["my-anatole", "anatole"]
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
# Enable Disqus
#disqusShortname = ""
# Google Analytics
googleAnalytics = "G-YP8PLL40SK"
# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
# Localized dates requires Hugo version 0.87.0
localizedDates = true

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[related]
includeNewer = true
threshold = 80
toLower = true

[[related.indices]]
name = 'keywords'
weight = 100

[[related.indices]]
name = 'tags'
weight = 80

[params.utterances]
repo = "ritter4u/ritter4u.github.io"
issueTerm = "pathname"
theme = "preferred-color-scheme"
label = "comments"
crossorigin = "anonymous"
