# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
author = "Keunreol Park" 
baseurl = "https://ritter4u.github.io/" # Include trailing slash
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved." 
title = "Clarity" 
# canonifyurls = true
paginate = 10
#theme = "hugo-clarity"
theme = ["my-anatole", "anatole"]
#theme = ["myclarity", "hugo-clarity"]
#theme = "hugo-flex"
#theme = "bootstrap-bp-hugo-theme"
#theme = "minimal-bootstrap-hugo-theme"
disqusShortname = ""

DefaultContentLanguage = "en"
disableLanguages = ["pt"]

# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[extra.comment.utterances]
issue_term = "commant"
repo = "ritter4u/commants"
theme = "github-light"
