[[main]]
name = "Home"
url = ""
weight = -110

[[main]]
name = "Archives"
url = "/post/rich-content/"
weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
identifier = "Links"
name = "Links"
weight = -108
[[main]]
name = "GitHub"
parent = "Links"
url = "https://github.com/ritter4u"
[[main]]
name = "Notion"
parent = "Links"
url = "https://notion.so/"

[[main]]
name = "About"
url = "/about/"
weight = -107

# # social menu links

# [[social]]
# name = "github"
# type = "social"
# url = "https://github.com/ritter4u"
# weight = 1
# [[social]]
# name = "twitter"
# url = "https://twitter.com/#"
# weight = 2
# [[social]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/#"
# weight = 3
# [[social]]
# name = "rss"
# url = "index.xml"
# weight = 4

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
